# Site
repository: aeolian83/aeolian83.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jungki Son
#title: Senior Network System Administrator
email: aeolian83@gmail.com
website: https://github.com/aeolian83

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  aeolian83
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: aeolian83
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: aeolian83
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jungki Son and 
  I am interested in using deep learning to change the world. I have an interest in deep learning models based on convolutional layers, transformer-based natural language processing models, and generative models. I am expanding my understanding through personal projects little by little.

  I am most skilled in: <mark>python</mark> and <mark>TensorFlow</mark>, <mark>Pytorch</mark>


  안녕하세요. 딥러닝으로 세상을 바꾸는데 관심이 있는 손정기입니다. 저는 컨볼루션 레이어에 기반한 컴퓨터 비전 모델, 트랜스포머에 기반한 자연어처리 모델, 그리고 각종 생성모델 모두에 관심이 있습니다. 개인프로젝트를 통해 이해의 범위를 넓혀나가고 있는 중입니다. 

  주 사용 언어는 <mark>python</mark>이고, <mark>TensorFlow</mark>, <mark>Pytorch</mark> 모두로 모델 구현이 가능합니다. 


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Implementing a Robust Object Picking Algorithm(Robust Object Picking Algorithm 구현)
        link: https://youtu.be/srv-g49sDUk
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/AIFFEL-Robust/ffb6d_project_final
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          This project is part of the Deep Learning education program offered by ModuLabs (https://modulabs.co.kr/). There is active research on 6D Pose Estimation models to expedite the installation process of robots used in the industrial field. The project aims to explore methods for simplifying the use and training of Deep Learning models, specifically the 6D Pose Estimation model, which enables computers to directly perceive the position and orientation of objects.

          The FFB6D model, which is one of the 6D Pose Estimation models, has been modified based on it, and the modifications have been made to make it applicable with other Depth Cameras, as long as the Camera Parameters are provided, instead of the Depth Camera used by the original model.

          I was responsible for modifying the model's code and conducting model training as part of the project.

          이 프로젝트는 모두연(https://modulabs.co.kr/)의 Deep Learning 교육과정의 일환입니다. 산업분야에서 사용하는 로봇의 install과정을 단축시키기 위해 6D Pose Estimation모델의 연구가 활발합니다. 컴퓨터가 직접 물체의 위치와 방향을 인식하기 위한 Deep Learnig 모델인 6D Pose Estimation모델을 조금더 간편하게 사용하고 훈련시키는 방법을 연구하기 위한 프로젝트입니다. 

          6D Pose Estimation모델의 하나인 FFB6D 모델을 기반으로 수정했으며, 기존 모델이 사용한 Depth Camera가 아닌 다른 Depth Camera도 Camera Parameter만 있다면 적용 가능하도록 수정했습니다. 

          저는 모델의 코드 수정과 모델 훈련을 맡아 프로젝트를 진행했습니다.

      - layout: top-middle
        title: Multi Neural Machine Translation for English to Korean Dialect
        link: https://github.com/seuyon0101/saturi_lab_multi_nmt_low_resource
        # link_text: Project Website
        additional_links:
          - title:  seuyon0101/saturi_lab_multi_nmt_low_resource
            icon: fab fa-github
            url: https://github.com/seuyon0101/saturi_lab_multi_nmt_low_resource
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          The Sauturi Lab is a group dedicated to researching and writing papers on a multi NMT (Neural Machine Translation) model that translates English into five regional dialects in Korea (Chungcheong, Jeju, Gangwon, Gyeongsang, Jeolla).
          This group explores one-to-many translation methods related to Low-Resource Languages (LRL) and conducts experiments based on hypotheses.
          The project has social value as it can contribute to language preservation in Korea, and it provides an opportunity to contribute to the necessity and advancement of Korean LRL research.

          sauturi lab 은 영어에서 5개 지방 방언(충청, 제주, 강원, 경상, 전라)으로 번역하는 모델(multi NMT)에 대한 연구를 수행하고 논문을 작성하는 것을 목표로하는 모임입니다.
          이 모임은 Low-Resource Language(LRL)와 관련된 one-to-many translation 방법을 탐색하고 가설을 세우고 실험을 진행합니다.
          프로젝트는 우리나라 언어 보존에 도움을 줄 수 있어 사회적인 가치가 있고 한국어 LRL 연구에 필요성과 발전을 위해 기여할 수 있는 기회가 될 수 있습니다.



  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
